import type { PipelineResult, MutationTestResult } from '../mutation/types.js';
import type { Reporter } from './reporter.js';

function outcomeIcon(outcome: string): string {
  switch (outcome) {
    case 'killed':
      return ':white_check_mark:';
    case 'survived':
      return ':warning:';
    case 'timeout':
      return ':hourglass:';
    case 'no_coverage':
      return ':see_no_evil:';
    case 'error':
      return ':x:';
    default:
      return ':question:';
  }
}

function renderMutationDetails(mutations: MutationTestResult[], label: string): string[] {
  if (mutations.length === 0) return [];

  const lines: string[] = [];
  lines.push('');
  lines.push('<details>');
  lines.push(`<summary>${label} (${mutations.length})</summary>`);
  lines.push('');

  for (const r of mutations) {
    lines.push(`### \`${r.mutation.filePath}:${r.mutation.startLine}\` - ${r.mutation.category}`);
    lines.push(r.mutation.description);
    lines.push('');
    lines.push('```diff');
    for (const line of r.mutation.originalCode.split('\n')) {
      lines.push(`- ${line}`);
    }
    for (const line of r.mutation.mutatedCode.split('\n')) {
      lines.push(`+ ${line}`);
    }
    lines.push('```');
    lines.push('');
  }

  lines.push('</details>');
  return lines;
}

export class GithubReporter implements Reporter {
  report(result: PipelineResult): string {
    const lines: string[] = [];

    lines.push('## diffmut Report');
    lines.push('');
    lines.push(
      `**Mutation Score: ${result.mutationScore.toFixed(1)}%** (${result.killed} killed / ${result.totalMutations} total)`,
    );
    lines.push('');

    // Summary table
    lines.push('| Status | File | Mutation | Category |');
    lines.push('|--------|------|----------|----------|');

    const survived: MutationTestResult[] = [];
    const caught: MutationTestResult[] = [];

    for (const fileResult of result.fileResults) {
      for (const r of fileResult.results) {
        const icon = outcomeIcon(r.outcome);
        const file = `\`${r.mutation.filePath}:${r.mutation.startLine}\``;
        lines.push(`| ${icon} | ${file} | ${r.mutation.description} | ${r.mutation.category} |`);

        if (r.outcome === 'survived' || r.outcome === 'no_coverage') {
          survived.push(r);
        } else if (r.outcome === 'killed') {
          caught.push(r);
        }
      }
    }

    lines.push(...renderMutationDetails(survived, 'Uncaught mutations'));
    lines.push(...renderMutationDetails(caught, 'Caught mutations'));

    lines.push('');
    lines.push(
      `<sub>Token usage: ${result.totalTokenUsage.totalTokens.toLocaleString()} | Duration: ${(result.durationMs / 1000).toFixed(1)}s | Generated by diffmut</sub>`,
    );

    return lines.join('\n');
  }
}
