import type { PipelineResult, MutationTestResult } from '../mutation/types.js';
import type { Reporter } from './reporter.js';

function outcomeIcon(outcome: string): string {
  switch (outcome) {
    case 'killed':
      return ':white_check_mark:';
    case 'survived':
      return ':warning:';
    case 'timeout':
      return ':hourglass:';
    case 'error':
      return ':x:';
    default:
      return ':question:';
  }
}

export class GithubReporter implements Reporter {
  report(result: PipelineResult): string {
    const lines: string[] = [];

    lines.push('## Mutagen Report');
    lines.push('');
    lines.push(
      `**Mutation Score: ${result.mutationScore.toFixed(1)}%** (${result.killed} killed / ${result.totalMutations} total)`,
    );
    lines.push('');

    // Summary table
    lines.push('| Status | File | Mutation | Category |');
    lines.push('|--------|------|----------|----------|');

    const survived: MutationTestResult[] = [];

    for (const fileResult of result.fileResults) {
      for (const r of fileResult.results) {
        const icon = outcomeIcon(r.outcome);
        const file = `\`${r.mutation.filePath}:${r.mutation.startLine}\``;
        lines.push(`| ${icon} | ${file} | ${r.mutation.description} | ${r.mutation.category} |`);

        if (r.outcome === 'survived') {
          survived.push(r);
        }
      }
    }

    // Details for survived mutations
    if (survived.length > 0) {
      lines.push('');
      lines.push('<details>');
      lines.push(`<summary>Survived mutations (${survived.length})</summary>`);
      lines.push('');

      for (const r of survived) {
        lines.push(`### \`${r.mutation.filePath}:${r.mutation.startLine}\` - ${r.mutation.category}`);
        lines.push(r.mutation.description);
        lines.push('');
        lines.push('```diff');
        for (const line of r.mutation.originalCode.split('\n')) {
          lines.push(`- ${line}`);
        }
        for (const line of r.mutation.mutatedCode.split('\n')) {
          lines.push(`+ ${line}`);
        }
        lines.push('```');
        lines.push('');
      }

      lines.push('</details>');
    }

    lines.push('');
    lines.push(
      `<sub>Token usage: ${result.totalTokenUsage.totalTokens.toLocaleString()} | Duration: ${(result.durationMs / 1000).toFixed(1)}s | Generated by Mutagen</sub>`,
    );

    return lines.join('\n');
  }
}
